In [1]:
import torch

cpu


In [4]:
rand_int = torch.randint(-100, 100, (6,))
rand_int

tensor([-58, -77, -49,  36, -77, -21])

In [6]:
tensor = torch.tensor([[0.1, 2.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 2.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [8]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
input = torch.empty(2, 3)
input 

tensor([[1.3248e-34, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.6576e-21, 4.5825e-41]])

In [11]:
range = torch.arange(5)
range

tensor([0, 1, 2, 3, 4])

In [13]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])